/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Icon: typeof import('./src/components/Icon.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    NotFound: typeof import('./src/components/NotFound.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toolbar: typeof import('./src/components/Toolbar.vue')['default']
    YakumanCard: typeof import('./src/components/YakumanCard.vue')['default']
  }
}
